require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

# Metrics
Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/seeds.rb'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

# Rails
Rails/I18nLocaleTexts:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

# Performance
Performance/StringReplacement:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true