#!/usr/bin/env sh
set -e

if [ -d "dev_catalyst_front" ]; then
  (
    cd dev_catalyst_front
    npm run type-check
  )
fi

if [ -d "dev_catalyst_rails" ]; then
  (
    cd dev_catalyst_rails
    bundle exec rubocop --force-exclusion
  )
fi


